backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images" # 图片存这里
public_folder: "../../assets/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog" # CMS 把文章写进这里，Astro 从这里读
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Hero Image", name: "heroImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Price", name: "price", widget: "number", required: false}